### ISSUE TITLE
What plugin files do I add to my _plugins folder?

### ISSUE THREAD

**Issue by tomjohnson1492** [18F/jekyll_pages_api#13]
I'm really excited about this plugin. I think it might make a perfect tool to facilitate context-sensitive help for help sites. I incorporated the gem, but I'm not sure what plugin files I'm supposed to add to my _plugins folder. Can you be more explicit there? I generated the site but didn't see the pages.json file. I assume I don't have something installed (missing plugin files?) correctly. Thanks.

**Comment by afeld** [comment]
Hmm, if you add the gem to your Gemfile under the appropriate group, it should be auto-required and work out of the box, no extra ruby file required. Good feedback that that's not clear, though.

Is your code open somewhere that I can look at it? Going to close to keep the issue list clean, but happy to continue the conversation.

**Comment by tomjohnson1492** [comment]
Oh, you know what? I was looking for a pages.json file in the _site directory after building Jekyll. I didn't look in the api folder. Everything is working now. Awesome plugin!
