### ISSUE TITLE
Why is this a gem?

### ISSUE THREAD

**Issue by afeld** [18F/jekyll_pages_api#19]
From @tomjohnson1492:

> One thing I'm unclear about is why the Pages API plugin relies on a gem. Why not just format a json file with a loop? 
> 
> I ended up putting this into my search.json file:
> 
> ```
> ---
> layout: none
> ---
> [
>   {% for page in site.pages %}
>     {% if page.search == "include" %}
>     {
>       "title"    : "{{ page.title | escape }}",
>       "category" : "{{ page.category }}",
>       "url"      : "{{ site.baseurl }}{{ page.url }}",
>       "date"     : "{{ page.date }}",
>       "body": "{{ page.content | strip_html | strip_newlines | replace: '\', '\\\\' | replace: '"', '\\"' }}",
>       "excerpt": "{{ page.content | strip_html | strip_newlines | truncate: 140, '…' | replace: '\', '\\' | replace: '"', '\\"' }}"
>     } ,
>       {% endif %}
>   {% endfor %}
> 
>     {% for post in site.posts %}
>     {% if post.search == "include" %}
>     {
>       "title"    : "{{ post.title | escape }}",
>       "category" : "{{ post.category }}",
>       "tags"     : "{{ post.tags | array_to_sentence_string }}",
>       "url"      : "{{ site.baseurl }}{{ post.url }}",
>       "date"     : "{{ post.date }}",
>       "body": "{{ post.content | strip_html | strip_newlines | replace: '\', '\\\\' | replace: '"', '\\"' }}",
>       "excerpt": "{{ post.content | strip_html | strip_newlines | truncate: 140, '…' | replace: '\', '\\' | replace: '"', '\\"' }}"
>     } {% unless forloop.last %},{% endunless %}
>       {% endif %}
>   {% endfor %}
> ]
> ```
> 
> I need to learn more about json -- what makes it valid or invalid, etc. Just curious, though, what are the benefits of using the Pages API plugin instead of just creating a custom json file like this?

**Comment by afeld** [comment]
The impetus for this project was to have a drop-in way to [add search](https://github.com/18F/jekyll_pages_api/issues/12) to any Jekyll site. Of [the solutions I've come across](https://github.com/18F/jekyll_pages_api/issues/6), none of them check all the boxes of

* Working well (or at all)
* Having good test coverage
* Being distributed in a way that's easy to get bug fixes

A few reasons why I prefer a gem to providing the code as a Gist or something:

* It makes it easy to check all of the boxes above.
* It can be included in [three lines](https://github.com/18F/jekyll_pages_api#usage).
* As you've shown above, JSON escaping can be messy, so I much prefer doing it in Ruby than through Liquid filters.
* It can be easily [included in other Jekyll plugin gems](https://github.com/18F/jekyll_pages_api/issues/6#issuecomment-73833583).
* Makes ["dynamic" API endpoints](https://github.com/18F/jekyll_pages_api/issues/14) possible.

The downsides being:

* It might be more difficult to understand how it works for those who aren't programmers/Rubyists.
* It won't work for site builders that don't support custom plugins (e.g. GitHub Pages).

Does that make sense? This gem is only the backend piece having a full search plugin, but hopefully it's useful as a standalone thing.

> I need to learn more about json -- what makes it valid or invalid, etc.

It's thankfully a fairly simple format, though the full spec is at http://json.org/ if you're interested.

**Comment by tomjohnson1492** [comment]
Thanks for responding to my question. I think it's great to add it here.
