### ISSUE TITLE
Question: Can I use this with GH-Pages and/or 18F-Pages?

### ISSUE THREAD

**Issue by gbinal** [18F/jekyll_pages_api#35]
Without any further customizing, do you know if I could use this with a microsite running on github pages or 18f Pages?

**Comment by afeld** [comment]
* **GitHub Pages:** [not directly](https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/).
* **18F Pages (and Federalist):** Yep! All of the [Guides](https://pages.18f.gov/guides/) are using it (via the [Guides style](https://github.com/18F/guides-style) gem)
