### ISSUE TITLE
Document querying ability of the API

### ISSUE THREAD

**Issue by gbinal** [18F/jekyll_pages_api#36]
The `README` documents where to find the endpoint, but doesn't seem to speak to what querying abilities exist and/or how they would work.  I've tried [experimenting](https://pages.18f.gov/accessibility/api/v1/pages.json?title=Checklist) but no luck so far.  

if you are able to just confirm if it's possible and point me in the right direction, I'm happy to do a PR to the `README`.

**Comment by afeld** [comment]
Zero querying abilities, by design...it's a static API! You would have to do any filtering on the requester side. Excited to see your interest in this though!
