### ISSUE TITLE
Got the error while trying to install jekyll_pages_api plugin "There was an error while trying to load the gem 'jekyll_pages_api'. (Bundler::GemRequireError)"

### ISSUE THREAD

**Issue by remya-cn** [18F/jekyll_pages_api#40]
[root@cu560 testsite1]# jekyll serve --host=0.0.0.0 
/usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'jekyll_pages_api'. (Bundler::GemRequireError) Gem Load Error is: undefined method `render' for class `Jekyll::Site' Backtrace for gem load error is: /usr/local/share/gems/gems/jekyll_pages_api-0.1.6/lib/jekyll/site.rb:7:in `alias_method' /usr/local/share/gems/gems/jekyll_pages_api-0.1.6/lib/jekyll/site.rb:7:in `<class:Site>' /usr/local/share/gems/gems/jekyll_pages_api-0.1.6/lib/jekyll/site.rb:5:in `<module:Jekyll>' /usr/local/share/gems/gems/jekyll_pages_api-0.1.6/lib/jekyll/site.rb:4:in `<top (required)>' /usr/local/share/gems/gems/jekyll_pages_api-0.1.6/lib/jekyll_pages_api.rb:7:in `require_relative' /usr/local/share/gems/gems/jekyll_pages_api-0.1.6/lib/jekyll_pages_api.rb:7:in `<top (required)>' /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `require' /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require' /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each' /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require' /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each' /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require' /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler.rb:107:in `require' /usr/local/share/gems/gems/jekyll-3.4.3/lib/jekyll/plugin_manager.rb:37:in `require_from_bundler' /usr/local/share/gems/gems/jekyll-3.4.3/exe/jekyll:9:in `<top (required)>' /usr/local/bin/jekyll:23:in `load' /usr/local/bin/jekyll:23:in `<main>' Bundler Error Backtrace:         from /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:90:in `block (2 levels) in require'         from /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'         from /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'         from /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'         from /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'         from /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'         from /usr/local/share/gems/gems/jekyll-3.4.3/lib/jekyll/plugin_manager.rb:37:in `require_from_bundler'         from /usr/local/share/gems/gems/jekyll-3.4.3/exe/jekyll:9:in `<top (required)>'         from /usr/local/bin/jekyll:23:in `load'         from /usr/local/bin/jekyll:23:in `<main>'

I just followed the steps you have mentioned. I am using CentOS GNU/Linux

**Comment by remya-cn** [comment]
it actually worked now. I was trying it with sudo permission. that caused the issue i guess.

**Comment by afeld** [comment]
Hmm, that doesn't _seem_ like a permissions error...let us know if you run into it again!
